// react-backup/src/components/Swiper/index.tsx
import React, { useState, useRef } from 'react';
import './index.css';

interface SwiperItem {
  id: number;
  src: string;
  title: string;
  url?: string;
}

const Swiper: React.FC = () => {
  // 定义图片数据
  const swiperItems: SwiperItem[] = [
    {
      id: 1,
      src: 'https://bu.dusays.com/2025/08/29/68b16f22981d4.jpg',
      title: 'ThriveX 博客管理系统 - 控制端（新版）',
      url: 'https://github.com/LiuYuYang01/ThriveX-Admin',
    },
    {
      id: 2,
      src: 'https://bu.dusays.com/2025/08/09/689624f3698af.jpg',
      title: 'ThriveX 博客管理系统 - 前端',
      url: 'https://github.com/LiuYuYang01/ThriveX-Blog',
    },
    {
      id: 3,
      src: 'https://bu.dusays.com/2024/09/17/66e96ca781d49.png',
      title: 'ThriveX 博客管理系统 - 控制端（旧版）',
      url: 'https://github.com/LiuYuYang01/Thrive-Admin',
    },
    {
      id: 4,
      src: 'https://bu.dusays.com/2024/09/18/66ea606eb5aa1.png',
      title: '云上校园项目 - 用户端',
      url: 'https://daxin.net',
    },
    {
      id: 5,
      src: 'https://bu.dusays.com/2024/09/18/66ea605d89df7.png',
      title: '云上校园项目 - 控制端',
      url: 'https://daxin.net',
    },
    {
      id: 6,
      src: 'https://bu.dusays.com/2025/08/29/68b16f22981d4.jpg',
      title: '占位图',
      url: 'https://daxin.net',
    },
    {
      id: 7,
      src: 'https://bu.dusays.com/2025/08/09/689624f3698af.jpg',
      title: '占位图',
      url: 'https://daxin.net',
    },
    {
      id: 8,
      src: 'https://bu.dusays.com/2025/08/09/689624f3698af.jpg',
      title: '占位图',
      url: 'https://daxin.net',
    },
    {
      id: 9,
      src: 'https://bu.dusays.com/2025/08/09/689624f3698af.jpg',
      title: '占位图',
      url: 'https://daxin.net',
    },
  ];

  const [currentIndex, setCurrentIndex] = useState(2);
  const [isHovering, setIsHovering] = useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  // 处理手动切换
  const handlePrev = () => {
    setCurrentIndex((prevIndex) => (prevIndex === 0 ? swiperItems.length - 1 : prevIndex - 1));
  };

  const handleNext = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % swiperItems.length);
  };

  // 复制数组以实现无缝滚动效果
  const duplicatedItems = [...swiperItems, ...swiperItems];

  return (
    <div className="swiper-container">
      <h1 className="text-white text-3xl text-center relative top-32">我的作品 🥳</h1>

      <div className="banner" onMouseEnter={() => setIsHovering(true)} onMouseLeave={() => setIsHovering(false)}>
        <div
          className="img-wrapper"
          ref={containerRef}
          style={{
            transform: `translateX(-${currentIndex * (25 + 1.78)}vw)`,
            transition: isHovering ? 'none' : 'transform 0.5s ease',
          }}
        >
          {duplicatedItems.map((item, index) => (
            <div className="img-box" key={`${item.id}-${index}`} onClick={() => window.open(item.url)}>
              <div className="info">
                <h3>{item.title}</h3>
              </div>
              <img src={item.src} alt={item.title} />
            </div>
          ))}
        </div>
      </div>

      <div className="btn-group">
        <button className="last btn" onClick={handlePrev}>
          <svg className="icon left" viewBox="0 0 1024 1024" width="128" height="128">
            <path d="M862.485 481.154H234.126l203.3-203.3c12.497-12.497 12.497-32.758 0-45.255s-32.758-12.497-45.255 0L135.397 489.373c-12.497 12.497-12.497 32.758 0 45.254l256.774 256.775c6.249 6.248 14.438 9.372 22.627 9.372s16.379-3.124 22.627-9.372c12.497-12.497 12.497-32.759 0-45.255l-203.3-203.301h628.36c17.036 0 30.846-13.81 30.846-30.846s-13.81-30.846-30.846-30.846z" />
          </svg>
        </button>

        <button className="next btn" onClick={handleNext}>
          <svg className="icon right" viewBox="0 0 1024 1024" width="128" height="128">
            <path d="M862.485 481.154H234.126l203.3-203.3c12.497-12.497 12.497-32.758 0-45.255s-32.758-12.497-45.255 0L135.397 489.373c-12.497 12.497-12.497 32.758 0 45.254l256.774 256.775c6.249 6.248 14.438 9.372 22.627 9.372s16.379-3.124 22.627-9.372c12.497-12.497 12.497-32.759 0-45.255l-203.3-203.301h628.36c17.036 0 30.846-13.81 30.846-30.846s-13.81-30.846-30.846-30.846z" />
          </svg>
        </button>
      </div>
    </div>
  );
};

export default Swiper;

// src/components/Swiper/index.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

interface SwiperItem {
  id: number
  src: string
  title: string
  url?: string
}

const swiperItems = ref<SwiperItem[]>([
  {
    id: 1,
    src: 'https://bu.dusays.com/2025/08/29/68b16f22981d4.jpg',
    title: 'ThriveX 博客管理系统 - 控制端（新版）',
    url: 'https://github.com/LiuYuYang01/ThriveX-Admin',
  },
  {
    id: 2,
    src: 'https://bu.dusays.com/2025/08/09/689624f3698af.jpg',
    title: 'ThriveX 博客管理系统 - 前端',
    url: 'https://github.com/LiuYuYang01/ThriveX-Blog',
  },
  {
    id: 3,
    src: 'https://bu.dusays.com/2024/09/17/66e96ca781d49.png',
    title: 'ThriveX 博客管理系统 - 控制端（旧版）',
    url: 'https://github.com/LiuYuYang01/Thrive-Admin',
  },
  {
    id: 4,
    src: 'https://bu.dusays.com/2024/09/18/66ea606eb5aa1.png',
    title: '云上校园项目 - 用户端',
    url: 'https://daxin.net',
  },
  {
    id: 5,
    src: 'https://bu.dusays.com/2024/09/18/66ea605d89df7.png',
    title: '云上校园项目 - 控制端',
    url: 'https://daxin.net',
  },
  {
    id: 6,
    src: 'https://bu.dusays.com/2025/08/29/68b16f22981d4.jpg',
    title: '占位图',
    url: 'https://daxin.net',
  },
  {
    id: 7,
    src: 'https://bu.dusays.com/2025/08/09/689624f3698af.jpg',
    title: '占位图',
    url: 'https://daxin.net',
  },
  {
    id: 8,
    src: 'https://bu.dusays.com/2025/08/09/689624f3698af.jpg',
    title: '占位图',
    url: 'https://daxin.net',
  },
  {
    id: 9,
    src: 'https://bu.dusays.com/2025/08/09/689624f3698af.jpg',
    title: '占位图',
    url: 'https://daxin.net',
  },
])

const currentIndex = ref(2)
const isHovering = ref(false)
const containerRef = ref<HTMLDivElement>()
let autoPlayInterval: ReturnType<typeof setInterval> | null = null

// 复制数组以实现无缝滚动效果
const duplicatedItems = ref([...swiperItems.value, ...swiperItems.value])

const handlePrev = () => {
  currentIndex.value = currentIndex.value === 0 ? swiperItems.value.length - 1 : currentIndex.value - 1
}

const handleNext = () => {
  currentIndex.value = (currentIndex.value + 1) % swiperItems.value.length
}

const openUrl = (url?: string) => {
  if (url) window.open(url, '_blank')
}

// 自动播放
const startAutoPlay = () => {
  if (autoPlayInterval) clearInterval(autoPlayInterval)
  autoPlayInterval = setInterval(() => {
    if (!isHovering.value) {
      handleNext()
    }
  }, 3000)
}

const stopAutoPlay = () => {
  if (autoPlayInterval) {
    clearInterval(autoPlayInterval)
    autoPlayInterval = null
  }
}

onMounted(() => {
  startAutoPlay()
})

onUnmounted(() => {
  stopAutoPlay()
})
</script>

<template>
  <div ref="containerRef" class="swiper-container">
    <h1 class="text-white text-3xl text-center relative top-32">我的作品 🥳</h1>

    <div 
      class="banner" 
      @mouseenter="isHovering = true" 
      @mouseleave="isHovering = false"
    >
      <div
        class="img-wrapper"
        :style="{
          transform: `translateX(-${currentIndex * (25 + 1.78)}vw)`,
          transition: isHovering ? 'none' : 'transform 0.5s ease',
        }"
      >
        <div 
          v-for="(item, index) in duplicatedItems" 
          :key="`${item.id}-${index}`" 
          class="img-box" 
          @click="openUrl(item.url)"
        >
          <div class="info">
            <h3>{{ item.title }}</h3>
          </div>
          <img :src="item.src" :alt="item.title" />
        </div>
      </div>
    </div>

    <div class="btn-group">
      <button class="last btn" @click="handlePrev">
        <svg class="icon left" viewBox="0 0 1024 1024" width="128" height="128">
          <path d="M862.485 481.154H234.126l203.3-203.3c12.497-12.497 12.497-32.758 0-45.255s-32.758-12.497-45.255 0L135.397 489.373c-12.497 12.497-12.497 32.758 0 45.254l256.774 256.775c6.249 6.248 14.438 9.372 22.627 9.372s16.379-3.124 22.627-9.372c12.497-12.497 12.497-32.759 0-45.255l-203.3-203.301h628.36c17.036 0 30.846-13.81 30.846-30.846s-13.81-30.846-30.846-30.846z" />
        </svg>
      </button>

      <button class="next btn" @click="handleNext">
        <svg class="icon right" viewBox="0 0 1024 1024" width="128" height="128">
          <path d="M862.485 481.154H234.126l203.3-203.3c12.497-12.497 12.497-32.758 0-45.255s-32.758-12.497-45.255 0L135.397 489.373c-12.497 12.497-12.497 32.758 0 45.254l256.774 256.775c6.249 6.248 14.438 9.372 22.627 9.372s16.379-3.124 22.627-9.372c12.497-12.497 12.497-32.759 0-45.255l-203.3-203.301h628.36c17.036 0 30.846-13.81 30.846-30.846s-13.81-30.846-30.846-30.846z" />
        </svg>
      </button>
    </div>
  </div>
</template>

<style scoped>
.swiper-container {
  --post-spacing: 1.78vw;
  --post-size: 25vw;
  --mask-size: 100vw;
  position: relative;
  width: 100vw;
  height: 100vh;
  font-size: 62.5%;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  box-sizing: border-box;
}

.swiper-container * {
  box-sizing: border-box;
}

.swiper-container .title {
  position: absolute;
  left: 50%;
  top: 5%;
  transform: translate(-50%, -5%);
  z-index: 10;
}

.swiper-container .title p {
  font-size: 4rem;
  font-weight: 800;
  white-space: nowrap;
  padding: 10px 20px;
  border-radius: 10px;
  margin: 0;
}

.swiper-container .banner {
  overflow: hidden;
  position: relative;
  width: 100vw;
  height: calc(var(--post-size) / 0.72);
  mask: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNDQwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDE0NDAgNTAwIiBpZD0iaiI+CiAgPHBhdGggZmlsbD0icmdiKDIwMCwyMDAsMjAwKSIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMCAwczI3NS4wNCAxMDAgNzIwIDEwMFMxNDQwIDAgMTQ0MCAwdjUwMHMtMjc1LjA0LTEwMC03MjAtMTAwUzAgNTAwIDAgNTAwVjB6Ii8+Cjwvc3ZnPgo=);
  mask-repeat: no-repeat;
  mask-position: center;
  mask-size: var(--mask-size);
  position: absolute;
  top: 10%;
  background-repeat: repeat;
  background-size: 300px 300px;
}

.swiper-container .img-wrapper {
  display: flex;
  position: absolute;
  width: max-content;
  height: calc(var(--post-size) / 0.72);
  transform: translate(13.39vw, 0);
}

.swiper-container .img-box {
  height: 100%;
  margin-right: var(--post-spacing);
  position: relative;
  cursor: pointer;
  flex-shrink: 0;
}

.swiper-container .img-box .info {
  position: absolute;
  display: flex;
  flex-direction: column;
  justify-content: center;
  left: 0;
  top: 0;
  height: 100%;
  width: 100%;
  background: hsla(0, 0%, 9%, 0.5);
  text-align: center;
  color: #fff9f1;
  font-size: 2rem;
  opacity: 0;
  transition: opacity 0.3s ease;
  margin: 0;
}

.swiper-container .img-box:hover .info {
  opacity: 1;
}

.swiper-container .img-box img {
  width: var(--post-size);
  height: 100%;
  object-position: center;
  object-fit: cover;
  display: block;
}

.swiper-container .btn-group {
  height: 15vh;
  position: absolute;
  left: 50%;
  bottom: 5%;
  transform: translate(-50%, -50%);
  transition: opacity 1s;
  opacity: 0;
  display: flex;
  z-index: 10;
}

.swiper-container .banner:hover ~ .btn-group,
.swiper-container .btn-group:hover {
  opacity: 1;
}

.swiper-container .btn {
  width: 60px;
  height: 60px;
  border-radius: 50%;
  border: 1px solid #171717;
  background-color: #fff;
  margin: 10px;
  cursor: pointer;
  transition: 0.4s;
  box-sizing: border-box;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 0;
}

.swiper-container .btn:hover {
  transform: scale(1.2);
  background-color: #000;
}

.swiper-container .btn:hover .icon {
  fill: #fff;
}

.swiper-container .icon {
  width: 30px;
  height: 30px;
}

.swiper-container .right {
  transform: rotate(180deg);
}
</style>
